### ISSUE TITLE
Update policy for language validation for Rhea/3.2.0

### ISSUE THREAD

**Issue by Crizz0** [phpbb/documentation#106]
E.g.:
- new files
- viglink translation

**Comment by Crizz0** [comment]
If needed, i'm not sure, because this one is already up to date: https://github.com/phpbb/phpbb-translation-policies/blob/3.2.x/guidelines.md

**Comment by michaelcullum** [comment]
What do you mean?

**Comment by Crizz0** [comment]
First of all, we have a repository for the translation guidelines and validation policies.

This one: https://github.com/phpbb/phpbb-translation-policies

There are written down the validation rules: https://github.com/phpbb/phpbb-translation-policies/blob/3.2.x/validation.md 

Parts of these rules are 1:1 here, wrapped in someother stuff: https://area51.phpbb.com/docs/dev/32x/language/validation.html 

So at the moment i would need to maintain two files from two different repos and keep them up to date. 

Is it possible to use a INCLUDE command or something similar, to include the translation-policies into the "phpBB Development Documentation"? This would allow me to maintain only one repo and those file in it.

**Comment by Crizz0** [comment]
@michaelcullum Did you get my problem?

**Comment by DavidIQ** [comment]
@Crizz0 if further discussion is needed about the other repo and merging it to here start a new issue. Otherwise send a pr to do exactly that. 👍
