### ISSUE TITLE
Missing Information - Update 3.0 - 3.1

### ISSUE THREAD

**Issue by nachtelb** [phpbb/documentation#14]
On Page https://www.phpbb.com/support/docs/en/3.1/ug/upgradeguide/upgrade3/ i miss some information:

1. Going after this guide, the folder "cache" should be deleted. After this, the new folder is not writeable. I see 2 solutions: Telling the admin, not to delete but to empty the folder. Or telling the admin to set the writeable-rights. If the cache-folder is not writeable the database-update stops with error-message: cache not writeable.

2. Missing information: 7. Delete and rebuild the search-index after update.

3. Before starting the update you should tell the admin to think about the option to clear the database to a unmodded clean state with the 3.0.x-Tool because for 3.1 - until now - no database-cleanup-tool is available. Its not so easy to remove the bugs that are generated by old database-mod-changes. 

4. For updates from 3.0.12 to 3.1.1 its better to take the database-update.php from the update-package, isnt it? Going through all 3.0.x-database-updates is irritating the admin.

Why i'am telling you this here? I hope this is the right place. - see: https://tracker.phpbb.com/browse/WEBSITE-1176?jql=project%20%3D%20WEBSITE

Maybe the reported bug 1176 about .htaccesss should be integrated too.

**Comment by Noxwizard** [comment]
1. The updater should already purge the cache.
2. You should not need to rebuild the search index unless you are upgrading from 2.0.x
3. Most MODs do not cause problems and the few occasions where they do, they are typically cosmetic in the ACP
4. They are the same file.
