### ISSUE TITLE
<languagename>_<version> folder inside zip file

### ISSUE THREAD

**Issue by scootergrisen** [phpbb/documentation#150]
https://github.com/phpbb/documentation/blob/master/development/language/validation.rst says:
> The submitted `<languagename>_<version>.zip` must contain a `<languagename>_<version>` folder. The files from above should be placed in this folder.

But that dont sound smart that the zip file should contain a folder by the same name as the zip file. When you extract it you would get:
```
british_english_3_2_2/british_english_3_2_2/language/
british_english_3_2_2/british_english_3_2_2/ext/
british_english_3_2_2/british_english_3_2_2/styles/
```

This would be smarter:
```
british_english_3_2_2/language/
british_english_3_2_2/ext/
british_english_3_2_2/styles/
```

Also it says "The files from above" but there are none above.

**Comment by Crizz0** [comment]
Hi,

I don't see, how you would get:
> british_english_3_2_2/british_english_3_2_2/language/

If you have a _british_english_3_2_2.zip_ within a british_english_3_2_2/-folder, then you get:
> british_english_3_2_2/language
british_english_3_2_2/ext/
british_english_3_2_2/styles/

when you extract that. 

Your structure will only appear, if you click in your zip-programm on "extract to foldername 'british_english_3_2_2'".

@above thing: Yes, that is confusing.

**Comment by DavidIQ** [comment]
It happens in Windows when using the built in extractor, but I wouldn’t change the text for that.

**Comment by scootergrisen** [comment]
It properly happens because you select the british_english_3_2_2 folder and pack that instead of going into the folder, selecting ext/, language/ and style/ and pack them.

**Comment by Crizz0** [comment]
@DavidIQ Even so you can remove this marked name and you won't get the doubled folder names:
![windows-extract-tool](https://user-images.githubusercontent.com/1311778/38772159-b3369d82-4030-11e8-9ebc-832b2d84882e.PNG)

**Comment by DavidIQ** [comment]
Yes I know that, but it’s there by default.

**Comment by scootergrisen** [comment]
Strange...
7-Zip is giving me unlogical extraction.

I have always thought that the zip files did not contain a <languagename>_<version> folder in the root.
But it seems like they do.

If i right click british_english_3_2_2.zip and select '**Extract to "british_english_3_2_2/"**' and it contains a folder by the same name (british_english_3_2_2) in the root 7-Zip extracts:
british_english_3_2_2/language/
british_english_3_2_2/ext/
british_english_3_2_2/styles/

If it change the filename to "whatever" i do it same thing again i get:
whatever/british_english_3_2_2/language/
whatever/british_english_3_2_2/ext/
whatever/british_english_3_2_2/styles/

So 7-Zip ignores the root folder if it have the same file name as the root folder (without the ".zip" part).

I just find it ilogical that british_english_3_2_2.zip have to contain a british_english_3_2_2 folder for no reason.
And lets say you change the file name of british_english_3_2_2.zip to british_english_3_2_3.zip then the folder inside is still called british_english_3_2_2.
