### ISSUE TITLE
config.php in 3.1 update instructions

### ISSUE THREAD

**Issue by michaelcullum** [phpbb/documentation#17]
It should inform the user to delete the blank config.php in the 3.1 package before uploading as otherwise it might over-write their existing config.php

https://www.phpbb.com/community/viewtopic.php?p=13878596#p13878596

**Comment by Oyabun1** [comment]
The documentation has been updated but the change still hasn't been rolled out to phpbb.com

**Comment by Noxwizard** [comment]
The website team has already been informed that they need to update the
documentation on the website. There is nothing more we can do about it.

**Comment by michaelcullum** [comment]
This is waiting on a mechanism to update docs, which at this time doesn't exist. However, that is not this ticket, this ticket is resolved.
