### ISSUE TITLE
language/usage.rst needs update for 3.2

### ISSUE THREAD

**Issue by nickvergessen** [phpbb/documentation#21]
The logic was moved to `phpbb\language\language` instead of `phpbb\user`

@MateBartus did anything else change? https://github.com/phpbb/documentation/pull/20/files#diff-095e33362bf3f1179099f1e83357dfde

**Comment by MateBartus** [comment]
Actually nothing should have changed, the add_lang() logic is a bit different, but if someone uses the user class then it should not matter anyway (in the rst it is in this way).

**Comment by Nicofuma** [comment]
For 3.2:
 - twig lang() function: `{{ lang('my_key') }}`
 - language service
 - BC with /phpbb/user

**Comment by MateBartus** [comment]
I'm not sure if it should go into the doc is the change of the `user::lang` member var. The way core files used it in some places to check whether the `user` object is inited, was to use `if (empty($user->lang))` which is no longer works, and `user::is_setup()` method should be used instead. IMO this is only relevant if there is any possibility that extensions using something like this.

**Comment by VSEphpbb** [comment]
Handled by https://github.com/phpbb/documentation/pull/38
