### ISSUE TITLE
Tables broken by new responsive CSS

### ISSUE THREAD

**Issue by iMattPro** [phpbb/documentation#228]
https://github.com/phpbb/documentation/blob/91c02a3b895618808559fd226e9f695c61189e96/development/_static/css/phpbb.css#L14

This float left is breaking content that comes after a table in the docs.

<img width="1400" alt="Screen Shot 2021-04-11 at 9 24 44 AM" src="https://user-images.githubusercontent.com/303711/114312497-c3324680-9aa7-11eb-8040-34c48f897446.png">

Can we please use something other than float?

**Comment by iMattPro** [comment]
Maybe replace the float with 100% width on the table:

```
.wy-table-responsive table { width: 100%; }
```

**Comment by marc1706** [comment]
Ah ok. Yes, changing the CSS like mentioned should work as well.
