### ISSUE TITLE
Move tutorials from wiki to documentation

### ISSUE THREAD

**Issue by marc1706** [phpbb/documentation#254]
Some tutorials should be moved from the wiki:
- https://wiki.phpbb.com/Tutorial.Parsing_text
- https://wiki.phpbb.com/Tutorial.Template_syntax

**Comment by nomind60s** [comment]
A little birdie suggested to me that https://wiki.phpbb.com/Sphinx_Fulltext_Search should be added to above list.

**Comment by marc1706** [comment]
Closing as articles have been moved and wiki has been taken down.
