### ISSUE TITLE
Add filename to code examples

### ISSUE THREAD

**Issue by Derky** [phpbb/documentation#35]
As requested by @nickvergessen I'm adding this as an issue:

It's really useful to see the filename in example code like [Symfony's documentation has] (http://symfony.com/doc/current/book/controller.html#route-parameters-as-controller-arguments). I don't think it's necessary for all example code, but especially for large code blocks andcomplete files it is.

Maybe with /ext/ and the full path?
```
// ext/acme/demo/acp/main_module.php
```

E.g.
```php
// ext/acme/demo/acp/main_module.php
<?php
/**
 *
 * This file is part of the phpBB Forum Software package.
 *
 * @copyright (c) phpBB Limited <https://www.phpbb.com>
 * @license GNU General Public License, version 2 (GPL-2.0)
 *
 * For full copyright and license information, please see
 * the docs/CREDITS.txt file.
 *
 */

namespace acme\demo\acp;

class main_info
{
    public function module()
    {
        return array(
            'filename'      => '\acme\demo\acp\main_module',
            'title'         => 'ACP_DEMO_TITLE',
            'version'       => '1.0.0',
            'modes'         => array(
                'settings' => array(
                    'title' => 'ACP_DEMO',
                    'auth'  => 'ext_acme/demo && acl_a_board',
                    'cat'   => array('ACP_DEMO_TITLE'),
                ),
            ),
        );
    }
}
```

**Comment by nickvergessen** [comment]
Should be inside the `<?php` tag so it's not a syntax error, but yes. I think it's helpful.

**Comment by nickvergessen** [comment]
Should we only do that on full files, or also on part-files like:
https://github.com/phpbb/documentation/blob/3.1.x/development/migrations/data_changes.rst#example-1

**Comment by Derky** [comment]
I also think part-files when it makes sense (and possible without making up a filename)
