### ISSUE TITLE
twig documentation

### ISSUE THREAD

**Issue by Sajaki** [phpbb/documentation#64]
hi, 
is there a twig documentation ? i'm missing it here and it's not on the wiki either.

**Comment by paul999** [comment]
What kind of documentation are you looking for?

**Comment by Sajaki** [comment]
for example here in the templating wiki it's explained how to do a loop. 
[wiki](https://wiki.phpbb.com/Tutorial.Template_syntax) In Twig, it's probably different.

**Comment by paul999** [comment]
The old syntax still works. For twig documentation self you can look at thr twig site http://twig.sensiolabs.org/documentation

**Comment by VSEphpbb** [comment]
As Paul linked, Twig documentation is provided by its developers.

**Comment by Sajaki** [comment]
Thanks for the link, this tells me how Twig works, but I still have Phpbb integration questions. 
Can phpbb styles be made using twig ? 
Can an extension add twig files for a style that isn't twig based ? 
Can an extension add html files for a style that is written in twig ? 
Why should i choose Twig over phpbb templating ?

**Comment by paul999** [comment]
You should ask such questions in ext writers discussion at phpBB.com ;).

1. Yes
2. Yes
3. Yes
4. It is simply a different syntax (As he it is implemented in phpBB 3.1).
