### ISSUE TITLE
Updates master banch (3.2.x => 3.3.x)

### ISSUE THREAD

**Issue by Nicofuma** [phpbb/documentation#94]
Changes:
 - [ ] PHP x.x.x (to be determined)
 - [ ] phpBB 3.2.x

**Comment by marc1706** [comment]
Also should update rhea_doc.xml to proteus_doc.xml and then fix bamboo to properly build it.

**Comment by VSEphpbb** [comment]
I think the Documentation version switcher needs to be updated. Drop 3.1.x, make 3.3.x the default, while maintaining 3.2.x and master options.

**Comment by iMattPro** [comment]
This should be fixed by #226

**Comment by iMattPro** [comment]
@marc1706 Is this closable?

**Comment by marc1706** [comment]
I think so, yes.
